#!/usr/bin/env python3
# Parses Il2CppDumper dump.cs, extracts the field offsets and role enum we need,
# rewrites jni/offsets.h in place.
import re, sys, pathlib

if len(sys.argv) != 3:
    sys.exit("parse_offsets.py <dump.cs> <offsets.h>")

dump = pathlib.Path(sys.argv[1]).read_text(errors="ignore")
out  = pathlib.Path(sys.argv[2])

def cls(name):
    pat = re.compile(rf"class {re.escape(name)}\b.*?\n\{{(.+?)\n\}}", re.S)
    m = pat.search(dump)
    return m.group(1) if m else ""

def field_off(body, field):
    m = re.search(rf"\b\w[\w<>]*\s+{re.escape(field)};\s*//\s*0x([0-9A-Fa-f]+)", body)
    return int(m.group(1), 16) if m else None

def role_enum():
    body = cls("RoleTypes")
    if not body:
        return {}
    pairs = re.findall(r"public const \w+ (\w+)\s*=\s*(\d+)", body)
    return {name: int(v) for name, v in pairs}

pc  = cls("PlayerControl")
pp  = cls("PlayerPhysics")
pi  = cls("PlayerInfo")
col = cls("Collider2D")

roles = role_enum()

def E(name, default):
    return roles.get(name, default)

vals = {
    "PC_PlayerId":     field_off(pc,  "PlayerId")     or 0x38,
    "PC_MyPhysics":    field_off(pc,  "MyPhysics")    or 0x50,
    "PC_Data":         field_off(pc,  "cachedData")   or field_off(pc, "Data") or 0x58,
    "PC_Collider2D":   field_off(pc,  "myCollider")   or 0x60,
    "PC_NetTransform": field_off(pc,  "NetTransform") or 0x68,
    "PP_Speed":        field_off(pp,  "Speed")        or 0x28,
    "PP_Velocity":     field_off(pp,  "Velocity")     or 0x2C,
    "PI_PlayerId":     field_off(pi,  "PlayerId")     or 0x10,
    "PI_RoleType":     field_off(pi,  "RoleType")     or field_off(pi,"CurrentRoleType") or 0x30,
    "PI_IsDead":       field_off(pi,  "IsDead")       or 0x38,
    "PI_Object":       field_off(pi,  "Object")       or 0x40,
    "Cam_Zoom":        0x1C,
    "Col2D_Enabled":   field_off(col, "enabled")      or 0x30,
    "Role_Crew":       E("Crewmate", 0),
    "Role_Imp":        E("Impostor", 1),
    "Role_Sci":        E("Scientist", 2),
    "Role_Eng":        E("Engineer", 3),
    "Role_GA":         E("GuardianAngel", 4),
    "Role_Shift":      E("Shapeshifter", 5),
    "Role_CrewGh":     E("CrewmateGhost", 6),
    "Role_ImpGh":      E("ImpostorGhost", 7),
    "Role_Noise":      E("Noisemaker", 8),
    "Role_Track":      E("Tracker", 9),
    "Role_Phan":       E("Phantom", 10),
    "Role_Viper":      E("Viper", 11),
}

hdr = f"""#pragma once
// Auto-generated by scripts/parse_offsets.py from Il2CppDumper output.
namespace Off {{
    constexpr uintptr_t PC_PlayerId       = 0x{vals["PC_PlayerId"]:X};
    constexpr uintptr_t PC_MyPhysics      = 0x{vals["PC_MyPhysics"]:X};
    constexpr uintptr_t PC_Data           = 0x{vals["PC_Data"]:X};
    constexpr uintptr_t PC_Collider2D     = 0x{vals["PC_Collider2D"]:X};
    constexpr uintptr_t PC_NetTransform   = 0x{vals["PC_NetTransform"]:X};

    constexpr uintptr_t PP_Speed          = 0x{vals["PP_Speed"]:X};
    constexpr uintptr_t PP_Velocity       = 0x{vals["PP_Velocity"]:X};

    constexpr uintptr_t PI_PlayerId       = 0x{vals["PI_PlayerId"]:X};
    constexpr uintptr_t PI_RoleType       = 0x{vals["PI_RoleType"]:X};
    constexpr uintptr_t PI_IsDead         = 0x{vals["PI_IsDead"]:X};
    constexpr uintptr_t PI_Object         = 0x{vals["PI_Object"]:X};

    constexpr uintptr_t Cam_Zoom          = 0x{vals["Cam_Zoom"]:X};
    constexpr uintptr_t Col2D_Enabled     = 0x{vals["Col2D_Enabled"]:X};

    enum Role : int {{
        Crewmate     = {vals["Role_Crew"]},
        Impostor     = {vals["Role_Imp"]},
        Scientist    = {vals["Role_Sci"]},
        Engineer     = {vals["Role_Eng"]},
        GuardianAngel= {vals["Role_GA"]},
        Shapeshifter = {vals["Role_Shift"]},
        CrewmateGhost= {vals["Role_CrewGh"]},
        ImpostorGhost= {vals["Role_ImpGh"]},
        Noisemaker   = {vals["Role_Noise"]},
        Tracker      = {vals["Role_Track"]},
        Phantom      = {vals["Role_Phan"]},
        Viper        = {vals["Role_Viper"]},
    }};

    inline int UserRoleToGame(int u) {{
        switch (u) {{
            case 1: return Viper;
            case 2: return Shapeshifter;
            case 3: return Phantom;
            default: return Impostor;
        }}
    }}
}}
"""
out.write_text(hdr)
print(f"wrote {out}  ({len(vals)} fields)")
